# Generated by Django 4.2.8 on 2024-01-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='gst_no',
            new_name='trn_no',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='gst_type',
            new_name='trn_type',
        ),
    ]
