# Generated by Django 4.2.8 on 2024-01-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_purchasebilltransactionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasebill',
            old_name='bill_no',
            new_name='tot_bill_no',
        ),
    ]
