# Generated by Django 4.2.3 on 2024-02-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0008_alter_purchasebill_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='state',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='balance',
        ),
    ]
